<a href="https://colab.research.google.com/github/ZiminPark/TIL/blob/master/tensorflow/code/get_layer_by_name.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import tensorflow as tf
import numpy as np

In [0]:
model = tf.keras.Sequential()
model.add(tf.keras.layers.GRU(20, name='want_to_find'))
model.add(tf.keras.layers.Dense(39))
model.add(tf.keras.layers.Dense(39))

print(model.layers)

[<tensorflow.python.keras.layers.recurrent_v2.GRU object at 0x7f51c801fa90>, <tensorflow.python.keras.layers.core.Dense object at 0x7f51c7f60710>, <tensorflow.python.keras.layers.core.Dense object at 0x7f51c7f609e8>]


In [0]:
sample = np.array([[[1.0,2.0,3.0]]], dtype=np.float32)

In [0]:
model.layers[0](sample)

<tf.Tensor: shape=(1, 20), dtype=float32, numpy=
array([[ 0.10883731,  0.34125784, -0.2764682 , -0.4479409 ,  0.09949609,
         0.01013871, -0.49761805,  0.06811239,  0.28774783, -0.33265346,
        -0.3720265 , -0.30939153,  0.23926798,  0.03866652,  0.12813671,
         0.16060154,  0.38302058, -0.1979138 ,  0.19868955, -0.13409604]],
      dtype=float32)>

In [0]:
model.get_layer('want_to_find')(sample)

<tf.Tensor: shape=(1, 20), dtype=float32, numpy=
array([[ 0.10883731,  0.34125784, -0.2764682 , -0.4479409 ,  0.09949609,
         0.01013871, -0.49761805,  0.06811239,  0.28774783, -0.33265346,
        -0.3720265 , -0.30939153,  0.23926798,  0.03866652,  0.12813671,
         0.16060154,  0.38302058, -0.1979138 ,  0.19868955, -0.13409604]],
      dtype=float32)>